port: 2017

timers:
  debut: 20
  recherche: 300
  soumission: 120
  resultat: 10
  inter_session: 120

web:
  dir: lib/web/scores
  bind: 0.0.0.0
  port: 8000

dictuonary:
  file: /assets/ods.txt
  wiktionary: false

game:
  grid:
   size: 15
  scrabble:
    score: {
      E: 1, A: 1, I: 1, N: 1, O: 1, R: 1, S: 1, T: 1, U: 1, L: 1,
      D: 2, M: 2, G: 2,
      B: 3, C: 3, P: 3,
      F: 4, H: 4, V: 4,
      J: 8, Q: 8,
      K: 10, W: 10, X: 10, Y: 10, Z: 10,
    }
  bag:
    pop: 7
    letters: {
      A: 9, B: 2, C: 2, D: 3,
      E: 15, F: 2, G: 2, H: 2,
      I: 8, J: 1, K: 1, L: 5,
      M: 3, N: 6, O: 6, P: 2,
      Q: 1, R: 6, S: 6, T: 6,
      U: 6, V: 2, W: 1, X: 1,
      Y: 1, Z: 1
    }